services:
  db:
    image: postgres:16-alpine
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventflow -d eventflow"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    environment:
      DATABASE_URL: postgresql://eventflow:eventflow@db:5432/eventflow
      DEBUG: "False"
      ENABLE_SECURE_HEADERS: "True"
      SECURE_SSL_REDIRECT: "False"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
