services:
  db:
    image: postgres:16-alpine
    container_name: eventflow-postgres
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: eventflow
      POSTGRES_PASSWORD: eventflow
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eventflow -d eventflow"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: eventflow-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eventflow-backend-prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DJANGO_SECRET_KEY: dev-insecure-key
      DJANGO_SETTINGS_MODULE: config.settings
      DEBUG: "False"
      ENABLE_SECURE_HEADERS: "True"
      SECURE_SSL_REDIRECT: "False"         # lokalnie bez TLS
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000"
      CSRF_TRUSTED_ORIGINS: "http://localhost:3000"
      DATABASE_URL: postgresql://eventflow:eventflow@db:5432/eventflow
      REDIS_URL: redis://redis:6379/0
      LOG_JSON: "True"
      SENTRY_ENVIRONMENT: "production"
      EMAIL_BACKEND: "django.core.mail.backends.console.EmailBackend"
      DEFAULT_FROM_EMAIL: "no-reply@example.com"
    ports:
      - "8000:8000"
    working_dir: /app
    command: >
      sh -c "
        python -m pip install --upgrade pip &&
        pip install -r requirements.txt &&
        python manage.py migrate &&
        gunicorn config.wsgi:application --bind 0.0.0.0:8000
      "

volumes:
  pgdata:
