services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: dev-insecure-key
      DEBUG: "True"
      ALLOWED_HOSTS: "*"
      REDIS_URL: redis://redis:6379/0
      EMAIL_BACKEND: django.core.mail.backends.locmem.EmailBackend
      DEFAULT_FROM_EMAIL: "EventFlow <no-reply@example.com>"
    depends_on:
      - redis
    volumes:
      - ./backend:/app
