# Generated by Django 5.2.4 on 2025-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
