# Generated by Django 5.2.4 on 2025-10-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_activationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organizer',
            field=models.BooleanField(default=False),
        ),
    ]
